control_points: # ゲームシーンコース
  - [0.0, 0.0, -20.0]
  - [0.0, 0.0, 20.0]

  - [0.0, 0.0, 480.0]
  - [15.0, 0.0, 495.0]
  - [20.0, 0.0, 500.0]

  - [480.0, 0.0, 500.0]
  - [495.0, 0.0, 495.0]
  - [500.0, 0.0, 480.0]

  - [500.0, 0.0, 20.0]
  - [495.0, 0.0, 5.0]
  - [480.0, 0.0, 0.0]

  - [20.0, 0.0, 0.0]
  - [5.0, 0.0, 5.0]
