control_points:
  - [0, 0, 0]
  - [0, 0, 60]
  - [0, 0, 120]
  - [0, 0, 180]
  - [0, 0, 240]
  - [0, 0, 300]
  - [0, 0, 360]
  - [0, 0, 420]
  - [0, 0, 480]
  - [0, 0, 540]
  - [0, 0, 600]
  - [0, 0, 900]
  - [0, 30, 1200]
  - [0, 300, 1500]
  - [0, 900, 2100]